// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fghyvuzhklnmflfwolxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaHl2dXpoa2xubWZsZndvbHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDQyNjAsImV4cCI6MjA2NDcyMDI2MH0.TpZFszAitylfeQ8Vvrvm0wADs2fCnyWhggXyVgLS7Yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);